//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "colaborator_role_pivot")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub colaborator_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub role_id: i32,
    #[sea_orm(belongs_to, from = "role_id", to = "id")]
    pub role: Option<super::role::Entity>,
    #[sea_orm(belongs_to, from = "colaborator_id", to = "id")]
    pub user: Option<super::user::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
