//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "colaborator_role_pivot")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub colaborator_id: i32,
    pub role_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::company_colaborator::Entity",
        from = "Column::ColaboratorId",
        to = "super::company_colaborator::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    CompanyColaborator,
    #[sea_orm(
        belongs_to = "super::company_role::Entity",
        from = "Column::RoleId",
        to = "super::company_role::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    CompanyRole,
}

impl Related<super::company_colaborator::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CompanyColaborator.def()
    }
}

impl Related<super::company_role::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CompanyRole.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
