//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "company_role")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub description: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::colaborator_role_pivot::Entity")]
    ColaboratorRolePivot,
}

impl Related<super::colaborator_role_pivot::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ColaboratorRolePivot.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
