//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "company")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub user_id: i32,
    #[sea_orm(has_many)]
    pub colaborators: HasMany<super::company_colaborator::Entity>,
    #[sea_orm(has_many)]
    pub roles: HasMany<super::company_role::Entity>
}

impl ActiveModelBehavior for ActiveModel {}
