//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "company_colaborator")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub company_id: i32,
    pub user_id: i32,
    pub document: String,
    pub badge: String,
    #[sea_orm(belongs_to, from = "company_id", to = "id")]
    pub company: HasOne<super::company::Entity>,
    #[sea_orm(has_many, via = "colaborator_role_pivot")]
    pub roles: HasMany<super::company_role::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
