//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "company_role")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub description: Option<String>,
    pub company_id: i32,
    #[sea_orm(has_one)]
    pub company: HasOne<super::company::Entity>,
    #[sea_orm(has_many, via = "company_role_pivot")]
    pub flags: HasMany<super::role::Entity>,
    #[sea_orm(has_many, via = "colaborator_role_pivot")]
    pub colaborators: HasMany<super::company_colaborator::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
