//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "company_role_pivot")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub company_role_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub flag_id: i32,
    #[sea_orm(belongs_to, from = "company_role_id", to = "id")]
    pub role: Option<super::company_role::Entity>,
    #[sea_orm(belongs_to, from = "flag_id", to = "id")]
    pub flag: Option<super::role::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
