//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "plan")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub price: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_one = "super::plan_feature_pivot::Entity")]
    PlanFeaturePivot,
}

impl Related<super::plan_feature_pivot::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PlanFeaturePivot.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
