//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "plan_feature_pivot")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub plan_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub feature_id: i32,

    #[sea_orm(belongs_to, from = "plan_id", to = "id")]
    pub plan: Option<super::plan::Entity>,
    #[sea_orm(belongs_to, from = "feature_id", to = "id")]
    pub feature: Option<super::role::Entity>
}

impl ActiveModelBehavior for ActiveModel {}