//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::colaborator_role_pivot::Entity as ColaboratorRolePivot;
pub use super::company::Entity as Company;
pub use super::company_colaborator::Entity as CompanyColaborator;
pub use super::company_role::Entity as CompanyRole;
pub use super::company_role_pivot::Entity as CompanyRolePivot;
pub use super::plan::Entity as Plan;
pub use super::plan_feature_pivot::Entity as PlanFeaturePivot;
pub use super::product::Entity as Product;
pub use super::role::Entity as Role;
pub use super::user::Entity as User;
pub use super::user_roles_pivot::Entity as UserRolesPivot;
