//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "role")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub name: String,
    pub description: Option<String>,
    #[sea_orm(has_many, via = "user_roles_pivot")]
    pub users: HasMany<super::user::Entity>
}

// #[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
// pub enum Relation {
//     #[sea_orm(has_many = "super::user_roles_pivot::Entity")]
//     UserRolesPivot,
// }

// impl Related<super::user::Entity> for Entity {
//     fn to() -> RelationDef {
//         super::user_roles_pivot::Relation::User.def()
//     }

//     fn via() -> Option<RelationDef> {
//         Some(super::user_roles_pivot::Relation::User.def().rev())
//     }
// }

// impl Related<super::plan::Entity> for Entity {
//     fn to() -> RelationDef {
//         super::plan_feature_pivot::Relation::Plan.def()
//     }

//     fn via() -> Option<RelationDef> {
//         Some(super::plan_feature_pivot::Relation::Plan.def().rev())
//     }
// }

impl ActiveModelBehavior for ActiveModel {}
