//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.15

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user_roles_pivot")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub role_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub user_id: i32,

    #[sea_orm(belongs_to, from = "user_id", to = "id")]
    pub user: Option<super::user::Entity>,

    #[sea_orm(belongs_to, from = "role_id", to = "id")]
    pub role: Option<super::role::Entity>,
}

// #[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
// pub enum Relation {
//     #[sea_orm(
//         belongs_to = "super::role::Entity",
//         from = "Column::RoleId",
//         to = "super::role::Column::Id",
//         on_update = "NoAction",
//         on_delete = "Cascade"
//     )]
//     Role,
//     #[sea_orm(
//         belongs_to = "super::user::Entity",
//         from = "Column::UserId",
//         to = "super::user::Column::Id",
//         on_update = "NoAction",
//         on_delete = "Cascade"
//     )]
//     User,
// }

// impl Related<super::role::Entity> for Entity {
//     fn to() -> RelationDef {
//         Relation::Role.def()
//     }
// }

// impl Related<super::user::Entity> for Entity {
//     fn to() -> RelationDef {
//         Relation::User.def()
//     }
// }

impl ActiveModelBehavior for ActiveModel {}
